### ISSUE TITLE
Add support for music.youtube.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/BlockYouTubeAdsShortcut#1]
### Issue URL (Ads)
 [https://music.youtube.com/watch?v=mU2e2ct9Vhg&list=RDAMVMWf1Ho9xmlOs](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmusic.youtube.com%2Fwatch%3Fv%3DmU2e2ct9Vhg%26list%3DRDAMVMWf1Ho9xmlOs)
### Comment
> Similar to Shortcut available for YouTube site, can we have something for music.YouTube.com as well?
> I must say, the shortcut on YT site works flawlessly, thanks.
> I was wondering if it’s scope could be expanded for music also.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/erHtEzO.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/kIdNWAp.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.1.1
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> Spam404, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/> AdGuard Experimental, <br/>AdGuard DNS

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/83300#issuecomment-846552665_

**Comment by VGisHere** [comment]
Also for music website, I basically added an OR condition when checking for url to support music.YouTube.com and surprisingly, it worked. 
However, a couple of issues I faced, there was no indication on logo stating if AG is active. 
Second, if I run it again, it would still run and give same notif as it ran first time unlike YouTube.com where we get indication that agscript is already running.

**Comment by lancelot-moon** [comment]
Is playing YouTube in the background by mobile browser possible?

**Comment by ameshkov** [comment]
> Is playing YouTube in the background by mobile browser possible?

Nope, I don't think that's possible.
