### ISSUE TITLE
Space when looking at comments of YouTube video

### ISSUE THREAD

**Issue by BottledSoda** [AdguardTeam/BlockYouTubeAdsShortcut#14]
Encountered with both AdGuard for iOS free and AdGuard for iOS Pro (with the Pro version though, I didn't explicitly send anything to any AG app).

**Comment by ameshkov** [comment]
Could you please make a screenshot of the issue, it's not clear from the description.

**Comment by BottledSoda** [comment]
![image](https://user-images.githubusercontent.com/98048296/151985861-66e014be-25bf-402f-91cc-4b2f654bd19c.png)

**Comment by BottledSoda** [comment]
![image](https://user-images.githubusercontent.com/98048296/151986865-e3b5f342-2929-4b19-a34d-74ceb234da0d.jpeg)

**Comment by ameshkov** [comment]
Hm, I see the screenshot, but I cannot reproduce this. It could be caused by some non-default filter list enabled in AdGuard, could you please try disabling lists one by one and see if it changes?

**Comment by BottledSoda** [comment]
I now have default filters and haven't reproduced the issue.
