### ISSUE TITLE
Execution error with MacOS (12.6)

### ISSUE THREAD

**Issue by beerisgood** [AdguardTeam/BlockYouTubeAdsShortcut#16]
![image](https://user-images.githubusercontent.com/9625159/194589421-e6e8156d-2025-4ff7-8f9f-11ee16819dec.png)

I get the following error message on macOS:

> the script must call the function "completion(result)" on exit.

**Comment by hadig** [comment]
You must modify the script a bit to work with macOS, see: https://www.icloud.com/shortcuts/c9aa512e52864016a31a70c25615e605

**Comment by beerisgood** [comment]
Thanks.

Unfortunately I got the message that I have to allow something in the developer options of Safari.
Since this goes too "far" for me, I will not use the script
