### ISSUE TITLE
Is automation possible?

### ISSUE THREAD

**Issue by VGisHere** [AdguardTeam/BlockYouTubeAdsShortcut#4]
I ain’t that familiar with shortcuts and different options that we have but I was trying to run this particular shortcut with automation on condition as follows -
On opening safari, if url contains “YouTube” run this shortcut else nothing.
I failed at this likely because Im missing some concept here.

The error I got stated, No web page found, cant run shortcut.
I tried many things around this, but couldn’t get through.
Any ideas?

also, “with AdGuard” seems a bit too long, any shorter version will be appreciated.
I changed it to “AG” for convenience in the script 😅

**Comment by ameshkov** [comment]
Unfortunately, I don't think that's possible. Anyways, if you come up with something viable, please let us know.
