### ISSUE TITLE
Non intrusive script run

### ISSUE THREAD

**Issue by VGisHere** [AdguardTeam/BlockYouTubeAdsShortcut#5]
Just a suggestion, 
Changing from Alert to notification removes the need of clicking OK, which kind of becomes frustrating each time shortcut is run.
I did few mods, but one strange thing I noticed.
When the script is run, it changes the contents of page within a second but it takes almost 3s for shortcut to complete and send notification. Not sure if it is an issue with Shortcuts app itself.

any ideas ?

**Comment by ameshkov** [comment]
I think you can simply remove the alert completely from the shortcut, there's no need to change the shortcut code for that.
