### ISSUE TITLE
Add support for youtube-nocookie.com

### ISSUE THREAD

**Issue by javabean** [AdguardTeam/BlockYouTubeAdsShortcut#7]
According to [Google Support article](https://support.google.com/youtube/answer/171780), YouTube also uses the domain www.youtube-nocookie.com to serve videos (and ads!).
We should add support for this domain in https://github.com/AdguardTeam/BlockYouTubeAdsShortcut/blob/2898c2a16fc1da1fb6667f45e0276a56e08cab66/index.js#L133-L146

**Comment by ameshkov** [comment]
The problem is that this domain is only used for embedding videos, you cannot visit it: https://www.youtube-nocookie.com/watch?v=2vLvq2iaqlI
